# --------------------------------------------------------------------------------
# ------------------------------------ MRF6S -------------------------------------
# -------------------- Generated by: MRFHelper (Version 2.1) ---------------------
# ------------------ (https://github.com/WenchenLie/MRFModeler) ------------------
# --------------------------------------------------------------------------------


wipe all;
model basic -ndm 2 -ndf 3;

# Basic model variables
set maxRunTime 600.0;  # $$$
set analysis_type "TH";  # $$$
set ShowAnimation 1;  # $$$
set MPCO 0;  # $$$

# Ground motion information
set MainFolder "H:/MRF_results/test/4SMRF";  # $$$
set GMname "th5";  # $$$
set SubFolder "th5";  # $$$
set GMdt 0.01;  # $$$
set GMpoints 5590;  # $$$
set GMduration 55.89;  # $$$
set FVduration 30;  # $$$
set EqSF 2.0;  # $$$
set GMFile "F:/MRF/GMs/$GMname.th";  # $$$
set subroutines "F:/MRF/subroutines";  # $$$
set temp "F:/MRF/temp";  # $$$

# Sourcing subroutines
cd $subroutines;
source DisplayModel3D.tcl;
source DisplayPlane.tcl;
source Spring_Zero.tcl;
source Spring_Rigid.tcl;
source PanelZone.tcl
source BeamHinge.tcl
source ColumnHinge.tcl
source TimeHistorySolver.tcl;
source PushoverAnalysis.tcl;
source CyclicPushover.tcl;

# Results folders
file mkdir $MainFolder;
file mkdir $MainFolder/$SubFolder;

# Basic parameters
set NStory 6;
set NBay 3;
set E 206000.00;
set mu 0.3;
set fy_beam 345.00;
set fy_column 345.00;
uniaxialMaterial Elastic 9 1.e-9;
uniaxialMaterial Elastic 99 1.e12;
geomTransf Linear 1;
geomTransf PDelta 2;
geomTransf Corotational 3;
set A_Stiff 1.e8;
set I_Stiff 1.e13;

# Building geometry
set Floor1 0.0;
set Floor2 4200.0;
set Floor3 8200.0;
set Floor4 12200.0;
set Floor5 16200.0;
set Floor6 20200.0;
set Floor7 24200.0;

set Axis1 0.0;
set Axis2 6100.0;
set Axis3 12200.0;
set Axis4 18300.0;
set Axis5 24400.0;

set HBuilding 24200.0;
set story_heights [list 4200 4000 4000 4000 4000 4000];


# ------------------------------------ Nodes -------------------------------------

# Support nodes
node 10010100 $Axis1 $Floor1;
node 10010200 $Axis2 $Floor1;
node 10010300 $Axis3 $Floor1;
node 10010400 $Axis4 $Floor1;
node 10010500 $Axis5 $Floor1;

# Leaning column grid nodes
node 10020500 $Axis5 $Floor2;
node 10030500 $Axis5 $Floor3;
node 10040500 $Axis5 $Floor4;
node 10050500 $Axis5 $Floor5;
node 10060500 $Axis5 $Floor6;
node 10070500 $Axis5 $Floor7;

# Leaning column connected nodes
node 10020502 $Axis5 $Floor2;
node 10020501 $Axis5 $Floor2;
node 10030502 $Axis5 $Floor3;
node 10030501 $Axis5 $Floor3;
node 10040502 $Axis5 $Floor4;
node 10040501 $Axis5 $Floor4;
node 10050502 $Axis5 $Floor5;
node 10050501 $Axis5 $Floor5;
node 10060502 $Axis5 $Floor6;
node 10060501 $Axis5 $Floor6;
node 10070502 $Axis5 $Floor7;

# Moment frame column nodes
node 10010101 $Axis1 $Floor1;  node 10010201 $Axis2 $Floor1;  node 10010301 $Axis3 $Floor1;  node 10010401 $Axis4 $Floor1;
node 10020102 $Axis1 [expr $Floor2 - 683.26/2];  node 10020202 $Axis2 [expr $Floor2 - 683.26/2];  node 10020302 $Axis3 [expr $Floor2 - 683.26/2];  node 10020402 $Axis4 [expr $Floor2 - 683.26/2];
node 10020101 $Axis1 [expr $Floor2 + 683.26/2];  node 10020201 $Axis2 [expr $Floor2 + 683.26/2];  node 10020301 $Axis3 [expr $Floor2 + 683.26/2];  node 10020401 $Axis4 [expr $Floor2 + 683.26/2];
node 10030102 $Axis1 [expr $Floor3 - 683.26/2];  node 10030202 $Axis2 [expr $Floor3 - 683.26/2];  node 10030302 $Axis3 [expr $Floor3 - 683.26/2];  node 10030402 $Axis4 [expr $Floor3 - 683.26/2];
node 10030101 $Axis1 [expr $Floor3 + 683.26/2];  node 10030201 $Axis2 [expr $Floor3 + 683.26/2];  node 10030301 $Axis3 [expr $Floor3 + 683.26/2];  node 10030401 $Axis4 [expr $Floor3 + 683.26/2];
node 10040102 $Axis1 [expr $Floor4 - 607.06/2];  node 10040202 $Axis2 [expr $Floor4 - 607.06/2];  node 10040302 $Axis3 [expr $Floor4 - 607.06/2];  node 10040402 $Axis4 [expr $Floor4 - 607.06/2];
node 10040101 $Axis1 [expr $Floor4 + 607.06/2];  node 10040201 $Axis2 [expr $Floor4 + 607.06/2];  node 10040301 $Axis3 [expr $Floor4 + 607.06/2];  node 10040401 $Axis4 [expr $Floor4 + 607.06/2];
node 10050102 $Axis1 [expr $Floor5 - 607.06/2];  node 10050202 $Axis2 [expr $Floor5 - 607.06/2];  node 10050302 $Axis3 [expr $Floor5 - 607.06/2];  node 10050402 $Axis4 [expr $Floor5 - 607.06/2];
node 10050101 $Axis1 [expr $Floor5 + 607.06/2];  node 10050201 $Axis2 [expr $Floor5 + 607.06/2];  node 10050301 $Axis3 [expr $Floor5 + 607.06/2];  node 10050401 $Axis4 [expr $Floor5 + 607.06/2];
node 10060102 $Axis1 [expr $Floor6 - 535.94/2];  node 10060202 $Axis2 [expr $Floor6 - 535.94/2];  node 10060302 $Axis3 [expr $Floor6 - 535.94/2];  node 10060402 $Axis4 [expr $Floor6 - 535.94/2];
node 10060101 $Axis1 [expr $Floor6 + 535.94/2];  node 10060201 $Axis2 [expr $Floor6 + 535.94/2];  node 10060301 $Axis3 [expr $Floor6 + 535.94/2];  node 10060401 $Axis4 [expr $Floor6 + 535.94/2];
node 10070102 $Axis1 [expr $Floor7 - 535.94/2];  node 10070202 $Axis2 [expr $Floor7 - 535.94/2];  node 10070302 $Axis3 [expr $Floor7 - 535.94/2];  node 10070402 $Axis4 [expr $Floor7 - 535.94/2];

# Moment frame beam nodes
node 10020104 [expr $Axis1 + 313.69] $Floor2;  node 10020205 [expr $Axis2 - 320.04] $Floor2;  node 10020204 [expr $Axis2 + 320.04] $Floor2;  node 10020305 [expr $Axis3 - 320.04] $Floor2;  node 10020304 [expr $Axis3 + 320.04] $Floor2;  node 10020405 [expr $Axis4 - 313.69] $Floor2;
node 10030104 [expr $Axis1 + 313.69] $Floor3;  node 10030205 [expr $Axis2 - 320.04] $Floor3;  node 10030204 [expr $Axis2 + 320.04] $Floor3;  node 10030305 [expr $Axis3 - 320.04] $Floor3;  node 10030304 [expr $Axis3 + 320.04] $Floor3;  node 10030405 [expr $Axis4 - 313.69] $Floor3;
node 10040104 [expr $Axis1 + 311.15] $Floor4;  node 10040205 [expr $Axis2 - 313.69] $Floor4;  node 10040204 [expr $Axis2 + 313.69] $Floor4;  node 10040305 [expr $Axis3 - 313.69] $Floor4;  node 10040304 [expr $Axis3 + 313.69] $Floor4;  node 10040405 [expr $Axis4 - 311.15] $Floor4;
node 10050104 [expr $Axis1 + 311.15] $Floor5;  node 10050205 [expr $Axis2 - 313.69] $Floor5;  node 10050204 [expr $Axis2 + 313.69] $Floor5;  node 10050305 [expr $Axis3 - 313.69] $Floor5;  node 10050304 [expr $Axis3 + 313.69] $Floor5;  node 10050405 [expr $Axis4 - 311.15] $Floor5;
node 10060104 [expr $Axis1 + 306.07] $Floor6;  node 10060205 [expr $Axis2 - 306.07] $Floor6;  node 10060204 [expr $Axis2 + 306.07] $Floor6;  node 10060305 [expr $Axis3 - 306.07] $Floor6;  node 10060304 [expr $Axis3 + 306.07] $Floor6;  node 10060405 [expr $Axis4 - 306.07] $Floor6;
node 10070104 [expr $Axis1 + 306.07] $Floor7;  node 10070205 [expr $Axis2 - 306.07] $Floor7;  node 10070204 [expr $Axis2 + 306.07] $Floor7;  node 10070305 [expr $Axis3 - 306.07] $Floor7;  node 10070304 [expr $Axis3 + 306.07] $Floor7;  node 10070405 [expr $Axis4 - 306.07] $Floor7;

# Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)







# Column splice ndoes
node 10030107 $Axis1 [expr $Floor3 + 0.5 * 4000.00];  node 10030207 $Axis2 [expr $Floor3 + 0.5 * 4000.00];  node 10030307 $Axis3 [expr $Floor3 + 0.5 * 4000.00];  node 10030407 $Axis4 [expr $Floor3 + 0.5 * 4000.00];
node 10050107 $Axis1 [expr $Floor5 + 0.5 * 4000.00];  node 10050207 $Axis2 [expr $Floor5 + 0.5 * 4000.00];  node 10050307 $Axis3 [expr $Floor5 + 0.5 * 4000.00];  node 10050407 $Axis4 [expr $Floor5 + 0.5 * 4000.00];

# Beam splice ndoes
node 10020208 [expr $Axis2 + 6100.00 / 2] $Floor2;
node 10030208 [expr $Axis2 + 6100.00 / 2] $Floor3;
node 10040208 [expr $Axis2 + 6100.00 / 2] $Floor4;
node 10050208 [expr $Axis2 + 6100.00 / 2] $Floor5;
node 10060208 [expr $Axis2 + 6100.00 / 2] $Floor6;
node 10070208 [expr $Axis2 + 6100.00 / 2] $Floor7;


# ----------------------------------- Elements -----------------------------------

set n 10.;

# Column elements
element elasticBeamColumn 10010101 10010101 10020102 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10010201 10010201 10020202 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10010301 10010301 10020302 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10010401 10010401 10020402 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;
element elasticBeamColumn 10020101 10020101 10030102 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10020201 10020201 10030202 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10020301 10020301 10030302 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10020401 10020401 10030402 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;
element elasticBeamColumn 10030102 10030101 10030107 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10030202 10030201 10030207 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10030302 10030301 10030307 33354.77 $E [expr ($n+1)/$n*2364194497.41] 2;  element elasticBeamColumn 10030402 10030401 10030407 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;
element elasticBeamColumn 10030103 10030107 10040102 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;  element elasticBeamColumn 10030203 10030207 10040202 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10030303 10030307 10040302 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10030403 10030407 10040402 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;
element elasticBeamColumn 10040101 10040101 10050102 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;  element elasticBeamColumn 10040201 10040201 10050202 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10040301 10040301 10050302 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10040401 10040401 10050402 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;
element elasticBeamColumn 10050102 10050101 10050107 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;  element elasticBeamColumn 10050202 10050201 10050207 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10050302 10050301 10050307 27741.88 $E [expr ($n+1)/$n*1906339929.25] 2;  element elasticBeamColumn 10050402 10050401 10050407 19548.35 $E [expr ($n+1)/$n*1248694276.80] 2;
element elasticBeamColumn 10050103 10050107 10060102 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10050203 10050207 10060202 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10050303 10050307 10060302 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10050403 10050407 10060402 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;
element elasticBeamColumn 10060101 10060101 10070102 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10060201 10060201 10070202 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10060301 10060301 10070302 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;  element elasticBeamColumn 10060401 10060401 10070402 15935.45 $E [expr ($n+1)/$n*986468478.67] 2;

# Beam elements
element elasticBeamColumn 10020104 10020104 10020205 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10020211 10020204 10020208 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10020212 10020208 10020305 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10020304 10020304 10020405 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;
element elasticBeamColumn 10030104 10030104 10030205 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10030211 10030204 10030208 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10030212 10030208 10030305 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;  element elasticBeamColumn 10030304 10030304 10030405 17806.42 $E [expr ($n+1)/$n*1361076761.71] 2;
element elasticBeamColumn 10040104 10040104 10040205 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10040211 10040204 10040208 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10040212 10040208 10040305 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10040304 10040304 10040405 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;
element elasticBeamColumn 10050104 10050104 10050205 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10050211 10050204 10050208 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10050212 10050208 10050305 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;  element elasticBeamColumn 10050304 10050304 10050405 14451.58 $E [expr ($n+1)/$n*874085993.76] 2;
element elasticBeamColumn 10060104 10060104 10060205 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10060211 10060204 10060208 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10060212 10060208 10060305 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10060304 10060304 10060405 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;
element elasticBeamColumn 10070104 10070104 10070205 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10070211 10070204 10070208 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10070212 10070208 10070305 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;  element elasticBeamColumn 10070304 10070304 10070405 12903.20 $E [expr ($n+1)/$n*616022509.89] 2;

# Panel zones
# PanelNone Floor Axis X Y E mu fy_column A_stiff I_stiff d_col d_beam tp tf bf transfTag type_ position check ""
PanelZone 2 1 $Axis1 $Floor2 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 683.26 24.45 27.69 327.66 2 1 "L";  PanelZone 2 2 $Axis2 $Floor2 $E $mu $fy_column $A_Stiff $I_Stiff 640.08 683.26 44.45 34.04 327.66 2 1 "I";  PanelZone 2 3 $Axis3 $Floor2 $E $mu $fy_column $A_Stiff $I_Stiff 640.08 683.26 44.45 34.04 327.66 2 1 "I";  PanelZone 2 4 $Axis4 $Floor2 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 683.26 24.45 27.69 327.66 2 1 "R";
PanelZone 3 1 $Axis1 $Floor3 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 683.26 24.45 27.69 327.66 2 1 "L";  PanelZone 3 2 $Axis2 $Floor3 $E $mu $fy_column $A_Stiff $I_Stiff 640.08 683.26 44.45 34.04 327.66 2 1 "I";  PanelZone 3 3 $Axis3 $Floor3 $E $mu $fy_column $A_Stiff $I_Stiff 640.08 683.26 44.45 34.04 327.66 2 1 "I";  PanelZone 3 4 $Axis4 $Floor3 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 683.26 24.45 27.69 327.66 2 1 "R";
PanelZone 4 1 $Axis1 $Floor4 $E $mu $fy_column $A_Stiff $I_Stiff 622.30 607.06 20.32 24.89 228.60 2 1 "L";  PanelZone 4 2 $Axis2 $Floor4 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 607.06 40.32 27.69 327.66 2 1 "I";  PanelZone 4 3 $Axis3 $Floor4 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 607.06 40.32 27.69 327.66 2 1 "I";  PanelZone 4 4 $Axis4 $Floor4 $E $mu $fy_column $A_Stiff $I_Stiff 622.30 607.06 20.32 24.89 228.60 2 1 "R";
PanelZone 5 1 $Axis1 $Floor5 $E $mu $fy_column $A_Stiff $I_Stiff 622.30 607.06 20.32 24.89 228.60 2 1 "L";  PanelZone 5 2 $Axis2 $Floor5 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 607.06 40.32 27.69 327.66 2 1 "I";  PanelZone 5 3 $Axis3 $Floor5 $E $mu $fy_column $A_Stiff $I_Stiff 627.38 607.06 40.32 27.69 327.66 2 1 "I";  PanelZone 5 4 $Axis4 $Floor5 $E $mu $fy_column $A_Stiff $I_Stiff 622.30 607.06 20.32 24.89 228.60 2 1 "R";
PanelZone 6 1 $Axis1 $Floor6 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 18.29 19.56 229.11 2 1 "L";  PanelZone 6 2 $Axis2 $Floor6 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 34.16 19.56 229.11 2 1 "I";  PanelZone 6 3 $Axis3 $Floor6 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 34.16 19.56 229.11 2 1 "I";  PanelZone 6 4 $Axis4 $Floor6 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 18.29 19.56 229.11 2 1 "R";
PanelZone 7 1 $Axis1 $Floor7 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 18.29 19.56 229.11 2 1 "LT";  PanelZone 7 2 $Axis2 $Floor7 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 34.16 19.56 229.11 2 1 "T";  PanelZone 7 3 $Axis3 $Floor7 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 34.16 19.56 229.11 2 1 "T";  PanelZone 7 4 $Axis4 $Floor7 $E $mu $fy_column $A_Stiff $I_Stiff 612.14 535.94 18.29 19.56 229.11 2 1 "RT";

# RBS elements (If RBS length equal zero, RBS element will not be generated)







# Beam hinges
# BeamHinge SpringID NodeI NodeJ E fy_beam Ix d htw bftf ry L Ls Lb My type_ {check ""}
BeamHinge 10020109 11020104 10020104 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10020210 10020205 11020202 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10020209 11020204 10020204 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5459.9 2730.0 2730.0 1571683308.24 2;  BeamHinge 10020310 10020305 11020302 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5459.9 2730.0 2730.0 1571683308.24 2;  BeamHinge 10020309 11020304 10020304 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10020410 10020405 11020402 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;
BeamHinge 10030109 11030104 10030104 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10030210 10030205 11030202 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10030209 11030204 10030204 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5459.9 2730.0 2730.0 1571683308.24 2;  BeamHinge 10030310 10030305 11030302 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5459.9 2730.0 2730.0 1571683308.24 2;  BeamHinge 10030309 11030304 10030304 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;  BeamHinge 10030410 10030405 11030402 $E $fy_beam 1361076761.71 683.26 49.43 6.71 53.84 5466.3 2733.1 2733.1 1571683308.24 2;
BeamHinge 10040109 11040104 10040104 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10040210 10040205 11040202 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10040209 11040204 10040204 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5472.6 2736.3 2736.3 1130707416.00 2;  BeamHinge 10040310 10040305 11040302 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5472.6 2736.3 2736.3 1130707416.00 2;  BeamHinge 10040309 11040304 10040304 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10040410 10040405 11040402 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;
BeamHinge 10050109 11050104 10050104 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10050210 10050205 11050202 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10050209 11050204 10050204 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5472.6 2736.3 2736.3 1130707416.00 2;  BeamHinge 10050310 10050305 11050302 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5472.6 2736.3 2736.3 1130707416.00 2;  BeamHinge 10050309 11050304 10050304 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;  BeamHinge 10050410 10050405 11050402 $E $fy_beam 874085993.76 607.06 48.95 6.61 48.75 5475.2 2737.6 2737.6 1130707416.00 2;
BeamHinge 10060109 11060104 10060104 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10060210 10060205 11060202 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10060209 11060204 10060204 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10060310 10060305 11060302 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10060309 11060304 10060304 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10060410 10060405 11060402 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;
BeamHinge 10070109 11070104 10070104 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10070210 10070205 11070202 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10070209 11070204 10070204 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10070310 10070305 11070302 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10070309 11070304 10070304 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;  BeamHinge 10070410 10070405 11070402 $E $fy_beam 616022509.89 535.94 43.53 6.04 45.68 5487.9 2743.9 2743.9 904565932.80 2;

# Column hinges
# Column SpringID NodeI NodeJ E Ix d htw ry L Lb My PPy SF_PPy pinned check ""
ColumnHinge 10010107 10010100 10010101 $E 1906339929.25 627.38 33.11 76.59 3858.37 3858.37 2363178499.44 0.1138 1.25 1;  ColumnHinge 10010207 10010200 10010201 $E 2364194497.41 640.08 28.69 77.31 3858.37 3858.37 2888957447.88 0.0631 1.25 1;  ColumnHinge 10010307 10010300 10010301 $E 2364194497.41 640.08 28.69 77.31 3858.37 3858.37 2888957447.88 0.0631 1.25 1;  ColumnHinge 10010407 10010400 10010401 $E 1906339929.25 627.38 33.11 76.59 3858.37 3858.37 2363178499.44 0.1138 1.25 1;
ColumnHinge 10020108 10020102 11020101 $E 1906339929.25 627.38 33.11 76.59 3858.37 3858.37 2363178499.44 0.1138 1.25 1;  ColumnHinge 10020208 10020202 11020201 $E 2364194497.41 640.08 28.69 77.31 3858.37 3858.37 2888957447.88 0.0631 1.25 1;  ColumnHinge 10020308 10020302 11020301 $E 2364194497.41 640.08 28.69 77.31 3858.37 3858.37 2888957447.88 0.0631 1.25 1;  ColumnHinge 10020408 10020402 11020401 $E 1906339929.25 627.38 33.11 76.59 3858.37 3858.37 2363178499.44 0.1138 1.25 1;
ColumnHinge 10020107 11020103 10020101 $E 1906339929.25 627.38 33.11 76.59 3316.74 3316.74 2363178499.44 0.0942 1.25 1;  ColumnHinge 10020207 11020203 10020201 $E 2364194497.41 640.08 28.69 77.31 3316.74 3316.74 2888957447.88 0.0522 1.25 1;  ColumnHinge 10020307 11020303 10020301 $E 2364194497.41 640.08 28.69 77.31 3316.74 3316.74 2888957447.88 0.0522 1.25 1;  ColumnHinge 10020407 11020403 10020401 $E 1906339929.25 627.38 33.11 76.59 3316.74 3316.74 2363178499.44 0.0942 1.25 1;
ColumnHinge 10030108 10030102 11030101 $E 1906339929.25 627.38 33.11 76.59 3316.74 3316.74 2363178499.44 0.0942 1.25 1;  ColumnHinge 10030208 10030202 11030201 $E 2364194497.41 640.08 28.69 77.31 3316.74 3316.74 2888957447.88 0.0522 1.25 1;  ColumnHinge 10030308 10030302 11030301 $E 2364194497.41 640.08 28.69 77.31 3316.74 3316.74 2888957447.88 0.0522 1.25 1;  ColumnHinge 10030408 10030402 11030401 $E 1906339929.25 627.38 33.11 76.59 3316.74 3316.74 2363178499.44 0.0942 1.25 1;
ColumnHinge 10030107 11030103 10030101 $E 1906339929.25 627.38 33.11 76.59 3354.84 3354.84 2363178499.44 0.0747 1.25 1;  ColumnHinge 10030207 11030203 10030201 $E 2364194497.41 640.08 28.69 77.31 3354.84 3354.84 2888957447.88 0.0414 1.25 1;  ColumnHinge 10030307 11030303 10030301 $E 2364194497.41 640.08 28.69 77.31 3354.84 3354.84 2888957447.88 0.0414 1.25 1;  ColumnHinge 10030407 11030403 10030401 $E 1906339929.25 627.38 33.11 76.59 3354.84 3354.84 2363178499.44 0.0747 1.25 1;
ColumnHinge 10040108 10040102 11040101 $E 1248694276.80 622.30 39.16 50.34 3354.84 3354.84 1582990382.40 0.1060 1.25 1;  ColumnHinge 10040208 10040202 11040201 $E 1906339929.25 627.38 33.11 76.59 3354.84 3354.84 2363178499.44 0.0498 1.25 1;  ColumnHinge 10040308 10040302 11040301 $E 1906339929.25 627.38 33.11 76.59 3354.84 3354.84 2363178499.44 0.0498 1.25 1;  ColumnHinge 10040408 10040402 11040401 $E 1248694276.80 622.30 39.16 50.34 3354.84 3354.84 1582990382.40 0.1060 1.25 1;
ColumnHinge 10040107 11040103 10040101 $E 1248694276.80 622.30 39.16 50.34 3392.94 3392.94 1582990382.40 0.0783 1.25 1;  ColumnHinge 10040207 11040203 10040201 $E 1906339929.25 627.38 33.11 76.59 3392.94 3392.94 2363178499.44 0.0368 1.25 1;  ColumnHinge 10040307 11040303 10040301 $E 1906339929.25 627.38 33.11 76.59 3392.94 3392.94 2363178499.44 0.0368 1.25 1;  ColumnHinge 10040407 11040403 10040401 $E 1248694276.80 622.30 39.16 50.34 3392.94 3392.94 1582990382.40 0.0783 1.25 1;
ColumnHinge 10050108 10050102 11050101 $E 1248694276.80 622.30 39.16 50.34 3392.94 3392.94 1582990382.40 0.0783 1.25 1;  ColumnHinge 10050208 10050202 11050201 $E 1906339929.25 627.38 33.11 76.59 3392.94 3392.94 2363178499.44 0.0368 1.25 1;  ColumnHinge 10050308 10050302 11050301 $E 1906339929.25 627.38 33.11 76.59 3392.94 3392.94 2363178499.44 0.0368 1.25 1;  ColumnHinge 10050408 10050402 11050401 $E 1248694276.80 622.30 39.16 50.34 3392.94 3392.94 1582990382.40 0.0783 1.25 1;
ColumnHinge 10050107 11050103 10050101 $E 1248694276.80 622.30 39.16 50.34 3428.50 3428.50 1582990382.40 0.0506 1.25 1;  ColumnHinge 10050207 11050203 10050201 $E 1906339929.25 627.38 33.11 76.59 3428.50 3428.50 2363178499.44 0.0238 1.25 1;  ColumnHinge 10050307 11050303 10050301 $E 1906339929.25 627.38 33.11 76.59 3428.50 3428.50 2363178499.44 0.0238 1.25 1;  ColumnHinge 10050407 11050403 10050401 $E 1248694276.80 622.30 39.16 50.34 3428.50 3428.50 1582990382.40 0.0506 1.25 1;
ColumnHinge 10060108 10060102 11060101 $E 986468478.67 612.14 45.87 49.66 3428.50 3428.50 1266392305.92 0.0621 1.25 1;  ColumnHinge 10060208 10060202 11060201 $E 986468478.67 612.14 45.87 49.66 3428.50 3428.50 1266392305.92 0.0414 1.25 1;  ColumnHinge 10060308 10060302 11060301 $E 986468478.67 612.14 45.87 49.66 3428.50 3428.50 1266392305.92 0.0414 1.25 1;  ColumnHinge 10060408 10060402 11060401 $E 986468478.67 612.14 45.87 49.66 3428.50 3428.50 1266392305.92 0.0621 1.25 1;
ColumnHinge 10060107 11060103 10060101 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0281 1.25 1;  ColumnHinge 10060207 11060203 10060201 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0188 1.25 1;  ColumnHinge 10060307 11060303 10060301 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0188 1.25 1;  ColumnHinge 10060407 11060403 10060401 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0281 1.25 1;
ColumnHinge 10070108 10070102 11070101 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0281 1.25 1;  ColumnHinge 10070208 10070202 11070201 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0188 1.25 1;  ColumnHinge 10070308 10070302 11070301 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0188 1.25 1;  ColumnHinge 10070408 10070402 11070401 $E 986468478.67 612.14 45.87 49.66 3464.06 3464.06 1266392305.92 0.0281 1.25 1;

# Rigid links
element truss 10020404 11020404 10020500 $A_Stiff 99;
element truss 10030404 11030404 10030500 $A_Stiff 99;
element truss 10040404 11040404 10040500 $A_Stiff 99;
element truss 10050404 11050404 10050500 $A_Stiff 99;
element truss 10060404 11060404 10060500 $A_Stiff 99;
element truss 10070404 11070404 10070500 $A_Stiff 99;

# Leaning column
element elasticBeamColumn 10010501 10010500 10020502 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10020501 10020501 10030502 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10030501 10030501 10040502 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10040501 10040501 10050502 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10050501 10050501 10060502 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10060501 10060501 10070502 $A_Stiff $E $I_Stiff 2;

# Leaning column hinges
Spring_Rigid 10020508 10020502 10020500;
Spring_Zero 10020507 10020500 10020501;
Spring_Rigid 10030508 10030502 10030500;
Spring_Zero 10030507 10030500 10030501;
Spring_Rigid 10040508 10040502 10040500;
Spring_Zero 10040507 10040500 10040501;
Spring_Rigid 10050508 10050502 10050500;
Spring_Zero 10050507 10050500 10050501;
Spring_Rigid 10060508 10060502 10060500;
Spring_Zero 10060507 10060500 10060501;
Spring_Rigid 10070508 10070502 10070500;

# --------------------------------- Constraints ----------------------------------

# Support
fix 10010100 1 1 1;
fix 10010200 1 1 1;
fix 10010300 1 1 1;
fix 10010400 1 1 1;
fix 10010500 1 1 0;

# Soil constraint
# (No soil constraint)

# Rigid diaphragm
equalDOF 11020204 11020104 1;  equalDOF 11020204 11020304 1;  equalDOF 11020204 11020404 1;
equalDOF 11030204 11030104 1;  equalDOF 11030204 11030304 1;  equalDOF 11030204 11030404 1;
equalDOF 11040204 11040104 1;  equalDOF 11040204 11040304 1;  equalDOF 11040204 11040404 1;
equalDOF 11050204 11050104 1;  equalDOF 11050204 11050304 1;  equalDOF 11050204 11050404 1;
equalDOF 11060204 11060104 1;  equalDOF 11060204 11060304 1;  equalDOF 11060204 11060404 1;
equalDOF 11070204 11070104 1;  equalDOF 11070204 11070304 1;  equalDOF 11070204 11070404 1;

# ---------------------------------- Recorders -----------------------------------

# Time
recorder Node -file $MainFolder/$SubFolder/Time.out -time -node 10010100 -dof 1 disp;

# Support reactions
recorder Node -file $MainFolder/$SubFolder/Support1.out -node 10010100 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support2.out -node 10010200 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support3.out -node 10010300 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support4.out -node 10010400 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support5.out -node 10010500 -dof 1 2 3 reaction;

# Story drift ratio
recorder Drift -file $MainFolder/$SubFolder/SDR1.out -iNode 10010100 -jNode 11020204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR2.out -iNode 11020204 -jNode 11030204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR3.out -iNode 11030204 -jNode 11040204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR4.out -iNode 11040204 -jNode 11050204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR5.out -iNode 11050204 -jNode 11060204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR6.out -iNode 11060204 -jNode 11070204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR_Roof.out -iNode 10010100 -jNode 11070204 -dof 1 -perpDirn 2;

# Floor acceleration
recorder Node -file $MainFolder/$SubFolder/RFA1.out -node 10010100 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA2.out -node 11020204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA3.out -node 11030204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA4.out -node 11040204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA5.out -node 11050204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA6.out -node 11060204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA7.out -node 11070204 -dof 1 accel;

# Floor velocity
recorder Node -file $MainFolder/$SubFolder/RFV1.out -node 10010100 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV2.out -node 11020204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV3.out -node 11030204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV4.out -node 11040204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV5.out -node 11050204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV6.out -node 11060204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV7.out -node 11070204 -dof 1 vel;

# Floor displacement
recorder Node -file $MainFolder/$SubFolder/Disp1.out -node 10010100 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp2.out -node 11020204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp3.out -node 11030204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp4.out -node 11040204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp5.out -node 11050204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp6.out -node 11060204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp7.out -node 11070204 -dof 1 disp;

# Shear forces
recorder Element -file $MainFolder/$SubFolder/Shear1_1.out -ele 10010101 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_2.out -ele 10010201 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_3.out -ele 10010301 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_4.out -ele 10010401 force;
recorder Element -file $MainFolder/$SubFolder/Shear2_1.out -ele 10020101 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_2.out -ele 10020201 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_3.out -ele 10020301 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_4.out -ele 10020401 force;
recorder Element -file $MainFolder/$SubFolder/Shear3_1.out -ele 10030102 force;  recorder Element -file $MainFolder/$SubFolder/Shear3_2.out -ele 10030202 force;  recorder Element -file $MainFolder/$SubFolder/Shear3_3.out -ele 10030302 force;  recorder Element -file $MainFolder/$SubFolder/Shear3_4.out -ele 10030402 force;
recorder Element -file $MainFolder/$SubFolder/Shear4_1.out -ele 10040101 force;  recorder Element -file $MainFolder/$SubFolder/Shear4_2.out -ele 10040201 force;  recorder Element -file $MainFolder/$SubFolder/Shear4_3.out -ele 10040301 force;  recorder Element -file $MainFolder/$SubFolder/Shear4_4.out -ele 10040401 force;
recorder Element -file $MainFolder/$SubFolder/Shear5_1.out -ele 10050102 force;  recorder Element -file $MainFolder/$SubFolder/Shear5_2.out -ele 10050202 force;  recorder Element -file $MainFolder/$SubFolder/Shear5_3.out -ele 10050302 force;  recorder Element -file $MainFolder/$SubFolder/Shear5_4.out -ele 10050402 force;
recorder Element -file $MainFolder/$SubFolder/Shear6_1.out -ele 10060101 force;  recorder Element -file $MainFolder/$SubFolder/Shear6_2.out -ele 10060201 force;  recorder Element -file $MainFolder/$SubFolder/Shear6_3.out -ele 10060301 force;  recorder Element -file $MainFolder/$SubFolder/Shear6_4.out -ele 10060401 force;

# Column springs
recorder Element -file $MainFolder/$SubFolder/ColSpring1_1T.out -ele 10010107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring1_2T.out -ele 10010207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring1_3T.out -ele 10010307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring1_4T.out -ele 10010407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring2_1B.out -ele 10020108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_2B.out -ele 10020208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_3B.out -ele 10020308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_4B.out -ele 10020408 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring2_1T.out -ele 10020107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_2T.out -ele 10020207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_3T.out -ele 10020307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_4T.out -ele 10020407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring3_1B.out -ele 10030108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_2B.out -ele 10030208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_3B.out -ele 10030308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_4B.out -ele 10030408 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring3_1T.out -ele 10030107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_2T.out -ele 10030207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_3T.out -ele 10030307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_4T.out -ele 10030407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring4_1B.out -ele 10040108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_2B.out -ele 10040208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_3B.out -ele 10040308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_4B.out -ele 10040408 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring4_1T.out -ele 10040107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_2T.out -ele 10040207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_3T.out -ele 10040307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring4_4T.out -ele 10040407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring5_1B.out -ele 10050108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_2B.out -ele 10050208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_3B.out -ele 10050308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_4B.out -ele 10050408 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring5_1T.out -ele 10050107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_2T.out -ele 10050207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_3T.out -ele 10050307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring5_4T.out -ele 10050407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring6_1B.out -ele 10060108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_2B.out -ele 10060208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_3B.out -ele 10060308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_4B.out -ele 10060408 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring6_1T.out -ele 10060107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_2T.out -ele 10060207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_3T.out -ele 10060307 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring6_4T.out -ele 10060407 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring7_1B.out -ele 10070108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring7_2B.out -ele 10070208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring7_3B.out -ele 10070308 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring7_4B.out -ele 10070408 material 3 stressStrain;

# Beam springs
recorder Element -file $MainFolder/$SubFolder/BeamSpring2_1R.out -ele 10020109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_2L.out -ele 10020210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_2R.out -ele 10020209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_3L.out -ele 10020310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_3R.out -ele 10020309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_4L.out -ele 10020410 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring3_1R.out -ele 10030109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_2L.out -ele 10030210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_2R.out -ele 10030209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_3L.out -ele 10030310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_3R.out -ele 10030309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_4L.out -ele 10030410 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring4_1R.out -ele 10040109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring4_2L.out -ele 10040210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring4_2R.out -ele 10040209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring4_3L.out -ele 10040310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring4_3R.out -ele 10040309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring4_4L.out -ele 10040410 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring5_1R.out -ele 10050109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring5_2L.out -ele 10050210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring5_2R.out -ele 10050209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring5_3L.out -ele 10050310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring5_3R.out -ele 10050309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring5_4L.out -ele 10050410 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring6_1R.out -ele 10060109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring6_2L.out -ele 10060210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring6_2R.out -ele 10060209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring6_3L.out -ele 10060310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring6_3R.out -ele 10060309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring6_4L.out -ele 10060410 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring7_1R.out -ele 10070109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring7_2L.out -ele 10070210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring7_2R.out -ele 10070209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring7_3L.out -ele 10070310 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring7_3R.out -ele 10070309 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring7_4L.out -ele 10070410 material 3 stressStrain;

# Panel zone springs (if any)
recorder Element -file $MainFolder/$SubFolder/PZ2_1.out -ele 11020100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ2_2.out -ele 11020200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ2_3.out -ele 11020300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ2_4.out -ele 11020400 material 1 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ3_1.out -ele 11030100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ3_2.out -ele 11030200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ3_3.out -ele 11030300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ3_4.out -ele 11030400 material 1 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ4_1.out -ele 11040100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ4_2.out -ele 11040200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ4_3.out -ele 11040300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ4_4.out -ele 11040400 material 1 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ5_1.out -ele 11050100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ5_2.out -ele 11050200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ5_3.out -ele 11050300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ5_4.out -ele 11050400 material 1 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ6_1.out -ele 11060100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ6_2.out -ele 11060200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ6_3.out -ele 11060300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ6_4.out -ele 11060400 material 1 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ7_1.out -ele 11070100 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ7_2.out -ele 11070200 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ7_3.out -ele 11070300 material 1 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ7_4.out -ele 11070400 material 1 stressStrain;

# MPCO recorder
if {$MPCO == 1} {
    recorder mpco $MainFolder$SubFolder/result.mpco -N displacement acceleration modesOfVibration -E material.stress material.strain;
}

# ------------------------------------- Mass -------------------------------------

# Moment frame mass
set g 9810.0;
mass 11020104 16.839 1.e-9 1.e-9;  mass 11020204 11.226 1.e-9 1.e-9;  mass 11020304 11.226 1.e-9 1.e-9;  mass 11020404 16.839 1.e-9 1.e-9;
mass 11030104 16.727 1.e-9 1.e-9;  mass 11030204 11.151 1.e-9 1.e-9;  mass 11030304 11.151 1.e-9 1.e-9;  mass 11030404 16.727 1.e-9 1.e-9;
mass 11040104 16.727 1.e-9 1.e-9;  mass 11040204 11.151 1.e-9 1.e-9;  mass 11040304 11.151 1.e-9 1.e-9;  mass 11040404 16.727 1.e-9 1.e-9;
mass 11050104 16.727 1.e-9 1.e-9;  mass 11050204 11.151 1.e-9 1.e-9;  mass 11050304 11.151 1.e-9 1.e-9;  mass 11050404 16.727 1.e-9 1.e-9;
mass 11060104 16.727 1.e-9 1.e-9;  mass 11060204 11.151 1.e-9 1.e-9;  mass 11060304 11.151 1.e-9 1.e-9;  mass 11060404 16.727 1.e-9 1.e-9;
mass 11070104 14.486 1.e-9 1.e-9;  mass 11070204 9.657 1.e-9 1.e-9;  mass 11070304 9.657 1.e-9 1.e-9;  mass 11070404 14.486 1.e-9 1.e-9;

# Leaning column mass
mass 10020500 266.340 1.e-9 1.e-9;
mass 10030500 265.817 1.e-9 1.e-9;
mass 10040500 265.817 1.e-9 1.e-9;
mass 10050500 265.817 1.e-9 1.e-9;
mass 10060500 265.817 1.e-9 1.e-9;
mass 10070500 255.360 1.e-9 1.e-9;


# -------------------------------- Eigen analysis --------------------------------

set pi [expr 2.0*asin(1.0)];
set nEigen 6
set lambdaN [eigen [expr $nEigen]];
set lambda1 [lindex $lambdaN 0];
set lambda2 [lindex $lambdaN 1];
set lambda3 [lindex $lambdaN 2];
set lambda4 [lindex $lambdaN 3];
set lambda5 [lindex $lambdaN 4];
set lambda6 [lindex $lambdaN 5];
set w1 [expr pow($lambda1, 0.5)];
set w2 [expr pow($lambda2, 0.5)];
set w3 [expr pow($lambda3, 0.5)];
set w4 [expr pow($lambda4, 0.5)];
set w5 [expr pow($lambda5, 0.5)];
set w6 [expr pow($lambda6, 0.5)];
set T1 [expr round(2.0*$pi/$w1 *1000.)/1000.];
set T2 [expr round(2.0*$pi/$w2 *1000.)/1000.];
set T3 [expr round(2.0*$pi/$w3 *1000.)/1000.];
set T4 [expr round(2.0*$pi/$w4 *1000.)/1000.];
set T5 [expr round(2.0*$pi/$w5 *1000.)/1000.];
set T6 [expr round(2.0*$pi/$w6 *1000.)/1000.];
puts "T1 = $T1 s";
puts "T2 = $T2 s";
puts "T3 = $T3 s";

set mode [list]
for {set i 1} {$i <= $NStory} {incr i} {
    lappend mode [expr [nodeEigenvector 11020204 $i 1]]
    lappend mode [expr [nodeEigenvector 11030204 $i 1]]
    lappend mode [expr [nodeEigenvector 11040204 $i 1]]
    lappend mode [expr [nodeEigenvector 11050204 $i 1]]
    lappend mode [expr [nodeEigenvector 11060204 $i 1]]
    lappend mode [expr [nodeEigenvector 11070204 $i 1]]
    set file_mode [open "$MainFolder/$SubFolder/mode$i.out" w]
    foreach val $mode {puts $file_mode $val}
    close $file_mode
    if {$i == 1} {set mode_list $mode}
    set mode [list]
};

set file_T [open "$MainFolder/$SubFolder/Period.out" w];
puts $file_T $T1;
puts $file_T $T2;
puts $file_T $T3;
puts $file_T $T4;
puts $file_T $T5;
puts $file_T $T6;
close $file_T;


# --------------------------- Static gravity analysis ----------------------------

pattern Plain 100 Linear {

    # Moment frame loads
    load 11020101 0. -187765.9 0.;      load 11020201 0. -125177.6 0.;      load 11020301 0. -125177.6 0.;      load 11020401 0. -187765.9 0.;
    load 11030101 0. -186667.9 0.;      load 11030201 0. -124445.6 0.;      load 11030301 0. -124445.6 0.;      load 11030401 0. -186667.9 0.;
    load 11040101 0. -186667.9 0.;      load 11040201 0. -124445.6 0.;      load 11040301 0. -124445.6 0.;      load 11040401 0. -186667.9 0.;
    load 11050101 0. -186667.9 0.;      load 11050201 0. -124445.6 0.;      load 11050301 0. -124445.6 0.;      load 11050401 0. -186667.9 0.;
    load 11060101 0. -186667.9 0.;      load 11060201 0. -124445.6 0.;      load 11060301 0. -124445.6 0.;      load 11060401 0. -186667.9 0.;
    load 11070101 0. -154661.2 0.;      load 11070201 0. -103107.8 0.;      load 11070301 0. -103107.8 0.;      load 11070401 0. -154661.2 0.;

    # gravity frame loads
    load 10020500 0. -3075525.5 0.;
    load 10030500 0. -3070145.2 0.;
    load 10040500 0. -3070145.2 0.;
    load 10050500 0. -3070145.2 0.;
    load 10060500 0. -3070145.2 0.;
    load 10070500 0. -2761607.2 0.;

}

wipeAnalysis
constraints Plain;
numberer RCM;
system BandGeneral;
test NormDispIncr 1.0e-5 60;
algorithm Newton;
integrator LoadControl 0.1;
analysis Static;
analyze 10;
loadConst -time 0.0;


# ---------------------------- Time history analysis -----------------------------

if {$ShowAnimation == 1} {DisplayModel3D DeformedShape 5.00 100 100 1600 1000};
set MF_FloorNodes [list 11020204 11030204 11040204 11050204 11060204 11070204];

if {$analysis_type == "TH"} {

    # Rayleigh damping
    set zeta 0.02;
    set a0 [expr $zeta*2.0*$w1*$w3/($w1 + $w3)];
    set a1 [expr $zeta*2.0/($w1 + $w3)];
    set a1_mod [expr $a1*(1.0+$n)/$n];
    set beam_Ids [list 10020104 10020211 10020212 10020304 10030104 10030211 10030212 10030304 10040104 10040211 10040212 10040304 10050104 10050211 10050212 10050304 10060104 10060211 10060212 10060304 10070104 10070211 10070212 10070304];
    set column_Ids [list 10010101 10010201 10010301 10010401 10020101 10020201 10020301 10020401 10030102 10030103 10030202 10030203 10030302 10030303 10030402 10030403 10040101 10040201 10040301 10040401 10050102 10050103 10050202 10050203 10050302 10050303 10050402 10050403 10060101 10060201 10060301 10060401];
    set mass_Ids [list 11020104 11020204 11020304 11020404 11020504 11020604 11030104 11030204 11030304 11030404 11030504 11030604 11040104 11040204 11040304 11040404 11040504 11040604 11050104 11050204 11050304 11050404 11050504 11050604 11060104 11060204 11060304 11060404 11060504 11060604 11070104 11070204 11070304 11070404 11070504 11070604 10020500 10030500 10040500 10050500 10060500 10070500];
    # region 1 -ele {*}$beam_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;
    # region 2 -ele {*}$column_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;
    # region 3 -ele {*}$mass_Ids -rayleigh $a0 0.0 0.0 0.0;
    rayleigh $a0 0.0 $a1 0.0;

    # Ground motion acceleration file input
    timeSeries Path 200 -dt $GMdt -filePath $GMFile -factor [expr $EqSF * $g];
    recorder Node -file $MainFolder/$SubFolder/groundmotion.out -timeSeries 200 -node 10010100 -dof 1 accel;
    pattern UniformExcitation 200 1 -accel 200;
    set totalTime [expr $GMduration + $FVduration];
    set CollapseDrift 0.1;  # $$$
    set MaxAnalysisDrift 0.5;
    set result [TimeHistorySolver $GMdt $totalTime $story_heights $MF_FloorNodes $CollapseDrift $MaxAnalysisDrift $GMname $maxRunTime $temp];
    set status [lindex $result 0];
    set controlled_time [lindex $result 1];
    puts "Running status: $status";
    puts "Controlled time: $controlled_time";

# ------------------------------ Pushover analysis -------------------------------

} elseif {$analysis_type == "PO"} {

    set m2 322.469;
    set m3 321.573;
    set m4 321.573;
    set m5 321.573;
    set m6 321.573;
    set m7 303.647;

    set F2 [expr $m2 * [lindex $mode_list 0]];
    set F3 [expr $m3 * [lindex $mode_list 1]];
    set F4 [expr $m4 * [lindex $mode_list 2]];
    set F5 [expr $m5 * [lindex $mode_list 3]];
    set F6 [expr $m6 * [lindex $mode_list 4]];
    set F7 [expr $m7 * [lindex $mode_list 5]];
    pattern Plain 222 Linear {
        load 11020204 $F2 0.0 0.0;
        load 11030204 $F3 0.0 0.0;
        load 11040204 $F4 0.0 0.0;
        load 11050204 $F5 0.0 0.0;
        load 11060204 $F6 0.0 0.0;
        load 11070204 $F7 0.0 0.0;
    };
    set CtrlNode 11070204;
    set maxRoofDrift 0.1;  # $$$
    set Dmax [expr $maxRoofDrift * $Floor7];
    set Dincr 0.5;
    set result [PushoverAnalysis $CtrlNode $Dmax $Dincr $maxRunTime];
    set status [lindex $result 0];
    set roofDisp [lindex $result 1];
    puts "Running status: $status";
    puts "Roof displacement: $roofDisp";
    puts "Roof drift ratio: [expr $roofDisp / $HBuilding]";

# ------------------------------- Cyclic pushover --------------------------------

} elseif {$analysis_type == "CP"} {

    set RDR_path [list 0 0.02 -0.02 0];  # $$$

    set m2 322.469;
    set m3 321.573;
    set m4 321.573;
    set m5 321.573;
    set m6 321.573;
    set m7 303.647;

    set F2 [expr $m2 * [lindex $mode_list 0]];
    set F3 [expr $m3 * [lindex $mode_list 1]];
    set F4 [expr $m4 * [lindex $mode_list 2]];
    set F5 [expr $m5 * [lindex $mode_list 3]];
    set F6 [expr $m6 * [lindex $mode_list 4]];
    set F7 [expr $m7 * [lindex $mode_list 5]];
    pattern Plain 222 Linear {
        load 11020204 $F2 0.0 0.0;
        load 11030204 $F3 0.0 0.0;
        load 11040204 $F4 0.0 0.0;
        load 11050204 $F5 0.0 0.0;
        load 11060204 $F6 0.0 0.0;
        load 11070204 $F7 0.0 0.0;
    };
    set CtrlNode 11070204;
    set Dincr 0.5;
    CyclicPushover $CtrlNode $RDR_path $HBuilding $Dincr $maxRunTime;

}

wipe all;


# ----------------------------- Building information -----------------------------
#
# Moment resisting frame model information
# Frame name: MRF6S
# Generation time: 2024-10-13 17:22:20.792278
# All units are in [N, mm, t]
# 
# 
# --------------- 1. Building Geometry ---------------
# 
# Building height: 24200
# Number of story: 6
# Number of bays: 3
# Plane dimensions [mm]: 42700 x 30500
# Number of moment frames: 2
# External column tributary area [mm]: 9150 x 3050
# Internal column tributary area [mm]: 6100 x 3050
# 
# 
# --------------- 2. Structural Components ---------------
# 
# Beam sections:
#  Floor  Bay-1  Bay-2  Bay-3
#      2 W27x94 W27x94 W27x94
#      3 W27x94 W27x94 W27x94
#      4 W24x76 W24x76 W24x76
#      5 W24x76 W24x76 W24x76
#      6 W21x68 W21x68 W21x68
#      7 W21x68 W21x68 W21x68
# 
# Column sections:
#  Story  Axis-1  Axis-2  Axis-3  Axis-4
#      1 W24x146 W24x176 W24x176 W24x146
#      2 W24x146 W24x176 W24x176 W24x146
#      3 W24x146 W24x176 W24x176 W24x146
#      4 W24x103 W24x146 W24x146 W24x103
#      5 W24x103 W24x146 W24x146 W24x103
#      6  W24x84  W24x84  W24x84  W24x84
# 
# Stories with column splices: 3, 5
# 
# Doubler plate thickness [mm]:
#  Floor  Axis-1  Axis-2  Axis-3  Axis-4
#      2  7.9375 25.4000 25.4000  7.9375
#      3  7.9375 25.4000 25.4000  7.9375
#      4  6.3500 23.8125 23.8125  6.3500
#      5  6.3500 23.8125 23.8125  6.3500
#      6  6.3500 22.2250 22.2250  6.3500
#      7  6.3500 22.2250 22.2250  6.3500
# 
# 
# --------------- 3. Load and Material ---------------
# 
# Material properties:
# 	Young's modulus [MPa]: 206000
# 	Nominal yield strength of beams [MPa]: 345
# 	Nominal yield strength of columns [MPa]: 345
# 	Possion ratio: 0.3
# 
# Load [MPa]:
# Story/Floor   Dead    Live  Cladding
#         1/2 0.0043 0.00240    0.0012
#         2/3 0.0043 0.00240    0.0012
#         3/4 0.0043 0.00240    0.0012
#         4/5 0.0043 0.00240    0.0012
#         5/6 0.0043 0.00240    0.0012
#         6/7 0.0043 0.00096    0.0012
# 
# Load and mass combination coefficients:
#         Dead  Live  Cladding
# Weight  1.05  0.25      1.05
# Mass    1.00  0.00      1.00
# 
# Axial compressive ratio of columns:
# Story   Axis-1   Axis-2   Axis-3   Axis-4
#    1b 0.113792 0.063096 0.063096 0.113792
#    1t 0.113792 0.063096 0.063096 0.113792
#    2b 0.094174 0.052218 0.052218 0.094174
#    2t 0.094174 0.052218 0.052218 0.094174
#    3b 0.074670 0.041403 0.041403 0.074670
#    3t 0.105968 0.049780 0.049780 0.105968
#    4b 0.078289 0.036778 0.036778 0.078289
#    4t 0.078289 0.036778 0.036778 0.078289
#    5b 0.050611 0.023775 0.023775 0.050611
#    5t 0.062085 0.041390 0.041390 0.062085
#    6b 0.028132 0.018755 0.018755 0.028132
#    6t 0.028132 0.018755 0.018755 0.028132
# 
# Seiemic weight of considered 2D frame: 21748.05 kN
# Seiemic mass of considered 2D frame: 1912.41 t
# 
# 
# --------------- 4. Connection and Boundary Condition ---------------
# 
# Base support: Fixed
# Beam-to-column connection: Fully constrained connection
# Consider panel zone deformation: Yes (Parallelogram)
# 

