# --------------------------------------------------------------------------------
# ----------------------------------- RC_2S2B ------------------------------------
# ------------------- Generated by: MRFHelper (Version 2.5.0) --------------------
# ------------------ (https://github.com/WenchenLie/MRFModeler) ------------------
# --------------------------------------------------------------------------------


wipe all;
model basic -ndm 2 -ndf 3;

# Basic model variables
set maxRunTime 600.0;  # $$$
set analysis_type "TH";  # $$$
set ShowAnimation 1;  # $$$
set MPCO 0;  # $$$

# Ground motion information
set MainFolder "H:/MRF_results/test/4SMRF";  # $$$
set GMname "th5";  # $$$
set SubFolder "th5";  # $$$
set GMdt 0.01;  # $$$
set GMpoints 5590;  # $$$
set GMduration 55.89;  # $$$
set FVduration 30;  # $$$
set EqSF 2.0;  # $$$
set GMFile "F:/Projects/OpenSAS/GMs/$GMname.th";  # $$$
set subroutines "F:/Projects/OpenSAS/subroutines";  # $$$
set temp "F:/Projects/OpenSAS/temp";  # $$$

# Sourcing subroutines
cd $subroutines;
source DisplayModel3D.tcl;
source DisplayPlane.tcl;
source Spring_Zero.tcl;
source Spring_Rigid.tcl;
source RCJoint2D.tcl
source RCHinge.tcl

source TimeHistorySolver.tcl;
source PushoverAnalysis.tcl;
source CyclicPushover.tcl;

# Results folders
file mkdir $MainFolder;
file mkdir $MainFolder/$SubFolder;

# Basic parameters
set NStory 2;
set NBay 2;
set E 30000.00;
set mu 0.2;
set fy_beam 460.00;
set fy_column 460.00;
uniaxialMaterial Elastic 9 1.e-9;
uniaxialMaterial Elastic 99 1.e12;
geomTransf Linear 1;
geomTransf PDelta 2;
geomTransf Corotational 3;
set A_Stiff 1.e8;
set I_Stiff 1.e13;

# Building geometry
set Floor1 0.0;
set Floor2 3600.0;
set Floor3 6900.0;

set Axis1 0.0;
set Axis2 6000.0;
set Axis3 12000.0;
set Axis4 18000.0;

set HBuilding 6900.0;
set story_heights [list 3600 3300];
set file_heights [open $MainFolder/heights.dat w]
foreach height $story_heights {
    puts $file_heights $height
}
close $file_heights


# ------------------------------------ Nodes -------------------------------------

# Support nodes
node 10010100 $Axis1 $Floor1;
node 10010200 $Axis2 $Floor1;
node 10010300 $Axis3 $Floor1;
node 10010400 $Axis4 $Floor1;

# Leaning column grid nodes
node 10020400 $Axis4 $Floor2;
node 10030400 $Axis4 $Floor3;

# Leaning column connected nodes
node 10020402 $Axis4 $Floor2;
node 10020401 $Axis4 $Floor2;
node 10030402 $Axis4 $Floor3;

# Moment frame column nodes
node 10010101 $Axis1 $Floor1;  node 10010201 $Axis2 $Floor1;  node 10010301 $Axis3 $Floor1;
node 10020102 $Axis1 [expr $Floor2 - 500.00/2];  node 10020202 $Axis2 [expr $Floor2 - 500.00/2];  node 10020302 $Axis3 [expr $Floor2 - 500.00/2];
node 10020101 $Axis1 [expr $Floor2 + 500.00/2];  node 10020201 $Axis2 [expr $Floor2 + 500.00/2];  node 10020301 $Axis3 [expr $Floor2 + 500.00/2];
node 10030102 $Axis1 [expr $Floor3 - 500.00/2];  node 10030202 $Axis2 [expr $Floor3 - 500.00/2];  node 10030302 $Axis3 [expr $Floor3 - 500.00/2];

# Moment frame beam nodes
node 10020104 [expr $Axis1 + 175.00] $Floor2;  node 10020205 [expr $Axis2 - 175.00] $Floor2;  node 10020204 [expr $Axis2 + 175.00] $Floor2;  node 10020305 [expr $Axis3 - 175.00] $Floor2;
node 10030104 [expr $Axis1 + 150.00] $Floor3;  node 10030205 [expr $Axis2 - 150.00] $Floor3;  node 10030204 [expr $Axis2 + 150.00] $Floor3;  node 10030305 [expr $Axis3 - 150.00] $Floor3;

# Beam spring nodes (If RBS length equal zero, beam spring nodes will not be generated)



# Column splice ndoes

# Beam splice ndoes




# ----------------------------------- Elements -----------------------------------
set n 10.;

# RC column elastic elements
element elasticBeamColumn 10010101 10010101 10020102 122500.0 $E [expr ($n+1)/$n*0.2*1250520833.333] 2;  element elasticBeamColumn 10010201 10010201 10020202 122500.0 $E [expr ($n+1)/$n*0.2*1250520833.333] 2;  element elasticBeamColumn 10010301 10010301 10020302 122500.0 $E [expr ($n+1)/$n*0.2*1250520833.333] 2;
element elasticBeamColumn 10020101 10020101 10030102 90000.0 $E [expr ($n+1)/$n*0.2*675000000.0] 2;  element elasticBeamColumn 10020201 10020201 10030202 90000.0 $E [expr ($n+1)/$n*0.2*675000000.0] 2;  element elasticBeamColumn 10020301 10020301 10030302 90000.0 $E [expr ($n+1)/$n*0.2*675000000.0] 2;

# RC beam elastic elements
element elasticBeamColumn 10020104 10020104 10020205 125000.0 $E [expr ($n+1)/$n*0.3*2604166666.667] 2;  element elasticBeamColumn 10020204 10020204 10020305 125000.0 $E [expr ($n+1)/$n*0.3*2604166666.667] 2;
element elasticBeamColumn 10030104 10030104 10030205 125000.0 $E [expr ($n+1)/$n*0.3*2604166666.667] 2;  element elasticBeamColumn 10030204 10030204 10030305 125000.0 $E [expr ($n+1)/$n*0.3*2604166666.667] 2;

# RC beam-column joints (nodes, material, and Joint2D element)
RCJoint2D 11020100 11020101 11020104 11020103 11020102 $Axis1 $Floor2 350.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;  RCJoint2D 11020200 11020201 11020204 11020203 11020202 $Axis2 $Floor2 350.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;  RCJoint2D 11020300 11020301 11020304 11020303 11020302 $Axis3 $Floor2 350.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;
RCJoint2D 11030100 11030101 11030104 11030103 11030102 $Axis1 $Floor3 300.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;  RCJoint2D 11030200 11030201 11030204 11030203 11030202 $Axis2 $Floor3 300.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;  RCJoint2D 11030300 11030301 11030304 11030303 11030302 $Axis3 $Floor3 300.0 500.0 Rigid 250.0 30000.0 0.2 1000.0;

# RC beam IMK hinges
RCHinge 10020109 11020104 10020104 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5650.0 0.3 10.0 0.0;  RCHinge 10020210 10020205 11020202 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5650.0 0.3 10.0 1.0;  RCHinge 10020209 11020204 10020204 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5650.0 0.3 10.0 0.0;  RCHinge 10020310 10020305 11020302 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5650.0 0.3 10.0 1.0;
RCHinge 10030109 11030104 10030104 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5700.0 0.3 10.0 0.0;  RCHinge 10030210 10030205 11030202 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5700.0 0.3 10.0 1.0;  RCHinge 10030209 11030204 10030204 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5700.0 0.3 10.0 0.0;  RCHinge 10030310 10030305 11030302 40.0 30000.0 460.0 200000.0 250.0 500.0 45.0 45.0 100.0 0.005026548246 0.005026548246 0.0 0.012566370614 1.0 0.0 1.0 5700.0 0.3 10.0 1.0;

# RC column IMK hinges
RCHinge 10010107 10010100 10010101 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.028836734694 1.0 3350.0 0.2 10.0 0.0;  RCHinge 10010207 10010200 10010201 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.057673469388 1.0 3350.0 0.2 10.0 0.0;  RCHinge 10010307 10010300 10010301 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.028836734694 1.0 3350.0 0.2 10.0 0.0;
RCHinge 10020108 10020102 11020101 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.028836734694 1.0 3350.0 0.2 10.0 1.0;  RCHinge 10020208 10020202 11020201 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.057673469388 1.0 3350.0 0.2 10.0 1.0;  RCHinge 10020308 10020302 11020301 40.0 30000.0 460.0 200000.0 350.0 350.0 45.0 45.0 100.0 0.005129130863 0.005129130863 0.0 0.00897597901 1.0 0.028836734694 1.0 3350.0 0.2 10.0 1.0;
RCHinge 10020107 11020103 10020101 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.018875 1.0 2800.0 0.2 10.0 0.0;  RCHinge 10020207 11020203 10020201 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.03775 1.0 2800.0 0.2 10.0 0.0;  RCHinge 10020307 11020303 10020301 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.018875 1.0 2800.0 0.2 10.0 0.0;
RCHinge 10030108 10030102 11030101 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.018875 1.0 2800.0 0.2 10.0 1.0;  RCHinge 10030208 10030202 11030201 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.03775 1.0 2800.0 0.2 10.0 1.0;  RCHinge 10030308 10030302 11030301 40.0 30000.0 460.0 200000.0 300.0 300.0 45.0 45.0 100.0 0.006981317008 0.006981317008 0.0 0.010471975512 1.0 0.018875 1.0 2800.0 0.2 10.0 1.0;

# Rigid links to leaning column
element truss 10020304 11020304 10020400 $A_Stiff 99;
element truss 10030304 11030304 10030400 $A_Stiff 99;

# Leaning column
element elasticBeamColumn 10010401 10010400 10020402 $A_Stiff $E $I_Stiff 2;
element elasticBeamColumn 10020401 10020401 10030402 $A_Stiff $E $I_Stiff 2;
Spring_Rigid 10020408 10020402 10020400;
Spring_Zero 10020407 10020400 10020401;
Spring_Rigid 10030408 10030402 10030400;

# --------------------------------- Constraints ----------------------------------
# Support
fix 10010100 1 1 1;
fix 10010200 1 1 1;
fix 10010300 1 1 1;
fix 10010400 1 1 0;

# Soil constraints

# Rigid diaphragm on ordinary beam-end nodes
equalDOF 10020204 10020104 1;
equalDOF 10020204 10020305 1;
equalDOF 10030204 10030104 1;
equalDOF 10030204 10030305 1;

# ---------------------------------- Recorders -----------------------------------

# Time
recorder Node -file $MainFolder/$SubFolder/Time.out -time -node 10010100 -dof 1 disp;

# Support reactions
recorder Node -file $MainFolder/$SubFolder/Support1.out -node 10010100 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support2.out -node 10010200 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support3.out -node 10010300 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support4.out -node 10010400 -dof 1 2 3 reaction;

# Story drift ratio
recorder Drift -file $MainFolder/$SubFolder/SDR1.out -iNode 10010100 -jNode 10020204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR2.out -iNode 10020204 -jNode 10030204 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR_Roof.out -iNode 10010100 -jNode 10030204 -dof 1 -perpDirn 2;

# Floor acceleration
recorder Node -file $MainFolder/$SubFolder/RFA1.out -node 10010100 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA2.out -node 10020204 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA3.out -node 10030204 -dof 1 accel;

# Floor velocity
recorder Node -file $MainFolder/$SubFolder/RFV1.out -node 10010100 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV2.out -node 10020204 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV3.out -node 10030204 -dof 1 vel;

# Floor displacement
recorder Node -file $MainFolder/$SubFolder/Disp1.out -node 10010100 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp2.out -node 10020204 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp3.out -node 10030204 -dof 1 disp;

# Shear forces
recorder Element -file $MainFolder/$SubFolder/Shear1_1.out -ele 10010101 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_2.out -ele 10010201 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_3.out -ele 10010301 force;
recorder Element -file $MainFolder/$SubFolder/Shear2_1.out -ele 10020101 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_2.out -ele 10020201 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_3.out -ele 10020301 force;

# Column springs
recorder Element -file $MainFolder/$SubFolder/ColSpring1_1T.out -ele 10010107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring1_2T.out -ele 10010207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring1_3T.out -ele 10010307 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring2_1B.out -ele 10020108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_2B.out -ele 10020208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_3B.out -ele 10020308 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring2_1T.out -ele 10020107 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_2T.out -ele 10020207 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring2_3T.out -ele 10020307 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/ColSpring3_1B.out -ele 10030108 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_2B.out -ele 10030208 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/ColSpring3_3B.out -ele 10030308 material 3 stressStrain;

# Beam springs
recorder Element -file $MainFolder/$SubFolder/BeamSpring2_1R.out -ele 10020109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_2L.out -ele 10020210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_2R.out -ele 10020209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring2_3L.out -ele 10020310 material 3 stressStrain;
recorder Element -file $MainFolder/$SubFolder/BeamSpring3_1R.out -ele 10030109 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_2L.out -ele 10030210 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_2R.out -ele 10030209 material 3 stressStrain;  recorder Element -file $MainFolder/$SubFolder/BeamSpring3_3L.out -ele 10030310 material 3 stressStrain;

# Panel zone springs (if any)
recorder Element -file $MainFolder/$SubFolder/PZ2_1.out -ele 11020100 material 5 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ2_2.out -ele 11020200 material 5 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ2_3.out -ele 11020300 material 5 stressStrain;
recorder Element -file $MainFolder/$SubFolder/PZ3_1.out -ele 11030100 material 5 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ3_2.out -ele 11030200 material 5 stressStrain;  recorder Element -file $MainFolder/$SubFolder/PZ3_3.out -ele 11030300 material 5 stressStrain;

# MPCO recorder
if {$MPCO == 1} {
    recorder mpco $MainFolder/$SubFolder/result.mpco -N displacement acceleration modesOfVibration -E material.stress material.strain;
}

# ------------------------------------- Mass -------------------------------------
set g 9810.0;
# Moment frame mass
mass 11020100 7.485 1.e-9 1.e-9 1.e-9;  mass 11020200 14.969 1.e-9 1.e-9 1.e-9;  mass 11020300 7.485 1.e-9 1.e-9 1.e-9;
mass 11030100 6.934 1.e-9 1.e-9 1.e-9;  mass 11030200 13.867 1.e-9 1.e-9 1.e-9;  mass 11030300 6.934 1.e-9 1.e-9 1.e-9;

# Leaning column mass
mass 10020400 2.112 1.e-9 1.e-9;
mass 10030400 1.010 1.e-9 1.e-9;

# -------------------------------- Eigen analysis --------------------------------

set pi [expr 2.0*asin(1.0)];
set nEigen 2
set lambdaN [eigen [expr $nEigen]];
set lambda1 [lindex $lambdaN 0];
set lambda2 [lindex $lambdaN 1];
set w1 [expr pow($lambda1, 0.5)];
set w2 [expr pow($lambda2, 0.5)];
set T1 [expr round(2.0*$pi/$w1 *1000.)/1000.];
set T2 [expr round(2.0*$pi/$w2 *1000.)/1000.];
puts "T1 = $T1 s";
puts "T2 = $T2 s";

set mode [list]
for {set i 1} {$i <= $NStory} {incr i} {
    lappend mode [expr [nodeEigenvector 10020204 $i 1]]
    lappend mode [expr [nodeEigenvector 10030204 $i 1]]
    set file_mode [open "$MainFolder/$SubFolder/mode$i.out" w]
    foreach val $mode {puts $file_mode $val}
    close $file_mode
    if {$i == 1} {set mode_list $mode}
    set mode [list]
};

set file_T [open "$MainFolder/$SubFolder/Period.out" w];
puts $file_T $T1;
puts $file_T $T2;
close $file_T;


# --------------------------- Static gravity analysis ----------------------------

pattern Plain 100 Linear {

    # Moment frame loads
    load 11020101 0. -73350.0 0.;      load 11020201 0. -146700.0 0.;      load 11020301 0. -73350.0 0.;
    load 11030101 0. -67950.0 0.;      load 11030201 0. -135900.0 0.;      load 11030301 0. -67950.0 0.;

    # gravity frame loads
    load 10020400 0. -20700.0 0.;
    load 10030400 0. -9900.0 0.;

}

wipeAnalysis
constraints Transformation;
numberer RCM;
system BandGeneral;
test NormDispIncr 1.0e-5 60;
algorithm Newton;
integrator LoadControl 0.1;
analysis Static;
set gravityStatus [analyze 10];
if {$gravityStatus != 0} {
    puts "WARNING: Static gravity analysis did not converge (OpenSees code: $gravityStatus, committed load factor: [getTime]). Continuing with the last committed state.";
}
loadConst -time 0.0;


# ---------------------------- Time history analysis -----------------------------

if {$ShowAnimation == 1} {DisplayModel3D DeformedShape 5.00 100 100 1600 1000};
set MF_FloorNodes [list 10020204 10030204];

if {$analysis_type == "TH"} {

    # Rayleigh damping
    set zeta 0.02;
    set a0 [expr $zeta*2.0*$w1*$w2/($w1 + $w2)];
    set a1 [expr $zeta*2.0/($w1 + $w2)];
    set a1_mod [expr $a1*(1.0+$n)/$n];
    set beam_Ids [list 10020104 10020204 10030104 10030204];
    set column_Ids [list 10010101 10010201 10010301 10020101 10020201 10020301];
    set mass_Ids [list 11020100 11020200 11020300 11030100 11030200 11030300 10020400 10030400];
    # region 1 -ele {*}$beam_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;
    # region 2 -ele {*}$column_Ids -rayleigh 0.0 0.0 $a1_mod 0.0;
    # region 3 -ele {*}$mass_Ids -rayleigh $a0 0.0 0.0 0.0;
    rayleigh $a0 0.0 $a1 0.0;

    # Ground motion acceleration file input
    timeSeries Path 200 -dt $GMdt -filePath $GMFile -factor [expr $EqSF * $g];
    recorder Node -file $MainFolder/$SubFolder/groundmotion.out -timeSeries 200 -node 10010100 -dof 1 accel;
    pattern UniformExcitation 200 1 -accel 200;
    set totalTime [expr $GMduration + $FVduration];
    set CollapseDrift 0.1;  # $$$
    set MaxAnalysisDrift 0.5;
    set result [TimeHistorySolver $GMdt $totalTime $story_heights $MF_FloorNodes $CollapseDrift $MaxAnalysisDrift $GMname $maxRunTime $temp];
    set status [lindex $result 0];
    set controlled_time [lindex $result 1];
    puts "Running status: $status";
    puts "Controlled time: $controlled_time";

# ------------------------------ Pushover analysis -------------------------------

} elseif {$analysis_type == "PO"} {

    set m2 32.051;
    set m3 28.745;

    set F2 [expr $m2 * $g * [lindex $mode_list 0]];
    set F3 [expr $m3 * $g * [lindex $mode_list 1]];
    set file_pattern [open $MainFolder/$SubFolder/Pattern.out w]
    puts $file_pattern $F2
    puts $file_pattern $F3
    close $file_pattern
    pattern Plain 222 Linear {
        load 10020204 $F2 0.0 0.0;
        load 10030204 $F3 0.0 0.0;
    };
    set CtrlNode 10030204;
    set maxRoofDrift 0.1;  # $$$
    set Dmax [expr $maxRoofDrift * $Floor3];
    set Dincr 0.5;
    set result [PushoverAnalysis $CtrlNode $Dmax $Dincr $maxRunTime];
    set status [lindex $result 0];
    set roofDisp [lindex $result 1];
    puts "Running status: $status";
    puts "Roof displacement: $roofDisp";
    puts "Roof drift ratio: [expr $roofDisp / $HBuilding]";

# ------------------------------- Cyclic pushover --------------------------------

} elseif {$analysis_type == "CP"} {

    set RDR_path [list 0 0.02 -0.02 0];  # $$$

    set m2 32.051;
    set m3 28.745;

    set F2 [expr $m2 * $g * [lindex $mode_list 0]];
    set F3 [expr $m3 * $g * [lindex $mode_list 1]];
    set file_pattern [open $MainFolder/$SubFolder/Pattern.out w]
    puts $file_pattern $F2
    puts $file_pattern $F3
    close $file_pattern
    pattern Plain 222 Linear {
        load 10020204 $F2 0.0 0.0;
        load 10030204 $F3 0.0 0.0;
    };
    set CtrlNode 10030204;
    set Dincr 0.5;
    set result [CyclicPushover $CtrlNode $RDR_path $HBuilding $Dincr $maxRunTime];
    set status [lindex $result 0];
    puts "Running status: $status";

}

set file_status [open "$MainFolder/$SubFolder/Status.dat" w]
puts $file_status $status
close $file_status
wipe all


# ----------------------------- Building information -----------------------------
#
# Reinforced-concrete moment resisting frame model information
# Frame name: RC_2S2B
# Generation time: 2026-08-18 16:42:48.931568
# Notes: Two-story RC concentrated-hinge and Joint2D example
# All units are in [N, mm, t]; strengths are expected values
# 
# 
# --------------- 1. Building Geometry ---------------
# 
# Building height: 6900
# Number of story: 2
# Number of bays: 2
# Plane dimensions [mm]: 12000 x 6000
# Number of moment frames: 2
# External column tributary area [mm]: 3000 x 3000
# Internal column tributary area [mm]: 6000 x 3000
# 
# 
# --------------- 2. Structural Components ---------------
# 
# Beam sections:
#  Floor    Bay-1    Bay-2
#      2 S250x500 S250x500
#      3 S250x500 S250x500
# 
# Column sections:
#  Story   Axis-1   Axis-2   Axis-3
#      1 S350x350 S350x350 S350x350
#      2 S300x300 S300x300 S300x300
# 
# 
# --------------- 3. Load and Material ---------------
# 
# Expected material properties:
# 	Concrete compressive strength fc [MPa]: 40.0
# 	Concrete elastic modulus Ec [MPa]: 30000.0
# 	Reinforcement yield strength fy [MPa]: 460.0
# 	Reinforcement elastic modulus Es [MPa]: 200000.0
# 	Poisson ratio: 0.2
# 
# Load [MPa]:
# Story/Floor  Dead  Live  Cladding
#         1/2 0.006 0.002     0.001
#         2/3 0.006 0.002     0.001
# 
# Load and mass combination coefficients:
#         Dead  Live  Cladding
# Weight   1.0   0.5       1.0
# Mass     1.0   0.5       1.0
# 
# Axial compressive ratio PPy of columns:
# Story   Axis-1   Axis-2   Axis-3
#    1b 0.028837 0.057673 0.028837
#    1t 0.028837 0.057673 0.028837
#    2b 0.018875 0.037750 0.018875
#    2t 0.018875 0.037750 0.018875
# 
# Seismic weight of considered 2D frame: 595.80 kN
# Seismic mass of considered 2D frame: 60.80 t
# 
# 
# --------------- 4. Connection and Boundary Condition ---------------
# 
# Base support: Fixed
# Beam-to-column connection: Concentrated RC hinges with Joint2D panel zones
# Joint panel model: Rigid
# Joint panel stiffness factor: 1000.0
# Rigid diaphragm constraint: Yes
# Soil constraints at floors: None
# 

