# --------------------------------------------------------------------------------
# -------------------------------- STKO_templete ---------------------------------
# -------------------- Generated by: MRFHelper (Version 1.2) ---------------------
# --------------------------------------------------------------------------------


wipe all;
model basic -ndm 2 -ndf 3;

# Basic model variables
set maxRunTime 600.0;  # $$$
set EQ 0;  # $$$
set PO 1;  # $$$
set ShowAnimation 1;  # $$$
set MPCO 0;  # $$$

# Ground motion information
set MainFolder "H:/MRF_results/test/4SMRF";  # $$$
set GMname "th5";  # $$$
set SubFolder "th5";  # $$$
set GMdt 0.01;  # $$$
set GMpoints 5590;  # $$$
set GMduration 55.89;  # $$$
set FVduration 30;  # $$$
set EqSF 2.0;  # $$$
set GMFile "F:/MRF/GMs/$GMname.th";  # $$$
set subroutines "F:/MRF/subroutines";  # $$$
set temp "F:/MRF/temp";  # $$$

# Sourcing subroutines
cd $subroutines;
source DisplayModel3D.tcl;
source DisplayPlane.tcl;
source Spring_Zero.tcl;
source Spring_Rigid.tcl;
source PanelZone.tcl
source BeamHinge.tcl
source ColumnHinge.tcl
source TimeHistorySolver.tcl;
source PushoverAnalysis.tcl;

# Results folders
file mkdir $MainFolder;
file mkdir $MainFolder/$SubFolder;

# Basic parameters
set NStory 6;
set NBay 3;
set E 206000.00;
set mu 0.3;
set fy_beam 345.00;
set fy_column 345.00;
uniaxialMaterial Elastic 9 1.e-9;
uniaxialMaterial Elastic 99 1.e12;
set A_Stiff 1.e8;
set I_Stiff 1.e13;

# Building geometry
set Floor1 0.0;
set Floor2 4300.0;
set Floor3 8300.0;
set Floor4 12300.0;
set Floor5 16300.0;
set Floor6 20300.0;
set Floor7 24300.0;

set Axis1 0.0;
set Axis2 6000.0;
set Axis3 9000.0;
set Axis4 15000.0;

set HBuilding 24300.0;
set story_heights [list 4300 4000 4000 4000 4000 4000];


# TODO ------------------------- Import STKO files -------------------------------

cd "F:/MRF/models/6SRCFnoWall_STKOfiles"
# Import nodes
source nodes.tcl;
# Import materials
source materials.tcl;
# Import sections
source sections.tcl;
# Import elements
source elements.tcl;
# Write constraints from analysis_steps.tcl
fix 25 1 1 1
fix 18 1 1 1
fix 28 1 1 1
fix 21 1 1 1
equalDOF 5 1   1
equalDOF 12 2   1
equalDOF 14 3   1
equalDOF 10 4   1
equalDOF 5 6   1
equalDOF 8 7   1
equalDOF 8 9   1
equalDOF 10 11   1
equalDOF 12 13   1
equalDOF 17 15   1
equalDOF 17 16   1
equalDOF 14 19   1
equalDOF 14 20   1
equalDOF 5 22   1
equalDOF 12 23   1
equalDOF 8 24   1
equalDOF 10 26   1
equalDOF 17 27   1
# Write control node of each floor
set MF_FloorNodes [list 17 10 5 12 14 8];


cd $subroutines;
# ---------------------------------- Recorders -----------------------------------

# Time
recorder Node -file $MainFolder/$SubFolder/Time.out -time -node 25 -dof 1 disp;

# Support reactions
recorder Node -file $MainFolder/$SubFolder/Support1.out -node 28 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support2.out -node 25 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support3.out -node 18 -dof 1 2 3 reaction;
recorder Node -file $MainFolder/$SubFolder/Support4.out -node 21 -dof 1 2 3 reaction;

# Story drift ratio
recorder Drift -file $MainFolder/$SubFolder/SDR1.out -iNode 25 -jNode 17 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR2.out -iNode 17 -jNode 10 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR3.out -iNode 10 -jNode 5  -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR4.out -iNode 5  -jNode 12 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR5.out -iNode 12 -jNode 14 -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR6.out -iNode 14 -jNode 8  -dof 1 -perpDirn 2;
recorder Drift -file $MainFolder/$SubFolder/SDR_Roof.out -iNode 25 -jNode 8 -dof 1 -perpDirn 2;

# Floor acceleration
recorder Node -file $MainFolder/$SubFolder/RFA1.out -node 25 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA2.out -node 17 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA3.out -node 10 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA4.out -node 5  -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA5.out -node 12 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA6.out -node 14 -dof 1 accel;
recorder Node -file $MainFolder/$SubFolder/RFA7.out -node 8  -dof 1 accel;

# Floor velocity
recorder Node -file $MainFolder/$SubFolder/RFV1.out -node 25 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV2.out -node 17 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV3.out -node 10 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV4.out -node 5  -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV5.out -node 12 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV6.out -node 14 -dof 1 vel;
recorder Node -file $MainFolder/$SubFolder/RFV7.out -node 8  -dof 1 vel;

# Floor displacement
recorder Node -file $MainFolder/$SubFolder/Disp1.out -node 25 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp2.out -node 17 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp3.out -node 10 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp4.out -node 5  -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp5.out -node 12 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp6.out -node 14 -dof 1 disp;
recorder Node -file $MainFolder/$SubFolder/Disp7.out -node 8  -dof 1 disp;

# Shear forces
recorder Element -file $MainFolder/$SubFolder/Shear1_1.out -ele 212 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_2.out -ele 174 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_3.out -ele 106 force;  recorder Element -file $MainFolder/$SubFolder/Shear1_4.out -ele 132 force;
recorder Element -file $MainFolder/$SubFolder/Shear2_1.out -ele 207 force;  recorder Element -file $MainFolder/$SubFolder/Shear2_2.out -ele 86  force;  recorder Element -file $MainFolder/$SubFolder/Shear2_3.out -ele 66  force;  recorder Element -file $MainFolder/$SubFolder/Shear2_4.out -ele 71  force;
recorder Element -file $MainFolder/$SubFolder/Shear3_1.out -ele 202 force;  recorder Element -file $MainFolder/$SubFolder/Shear3_2.out -ele 137 force;  recorder Element -file $MainFolder/$SubFolder/Shear3_3.out -ele 11  force;  recorder Element -file $MainFolder/$SubFolder/Shear3_4.out -ele 91  force;
recorder Element -file $MainFolder/$SubFolder/Shear4_1.out -ele 148 force;  recorder Element -file $MainFolder/$SubFolder/Shear4_2.out -ele 101 force;  recorder Element -file $MainFolder/$SubFolder/Shear4_3.out -ele 1   force;  recorder Element -file $MainFolder/$SubFolder/Shear4_4.out -ele 96  force;
recorder Element -file $MainFolder/$SubFolder/Shear5_1.out -ele 191 force;  recorder Element -file $MainFolder/$SubFolder/Shear5_2.out -ele 61  force;  recorder Element -file $MainFolder/$SubFolder/Shear5_3.out -ele 6   force;  recorder Element -file $MainFolder/$SubFolder/Shear5_4.out -ele 127 force;
recorder Element -file $MainFolder/$SubFolder/Shear6_1.out -ele 158 force;  recorder Element -file $MainFolder/$SubFolder/Shear6_2.out -ele 153 force;  recorder Element -file $MainFolder/$SubFolder/Shear6_3.out -ele 26  force;  recorder Element -file $MainFolder/$SubFolder/Shear6_4.out -ele 163 force;

# MPCO recorder
if {$MPCO == 1} {
    recorder mpco $MainFolder$SubFolder/result.mpco -N displacement acceleration modesOfVibration -E material.stress material.strain;
}


# -------------------------------- Eigen analysis --------------------------------

set pi [expr 2.0*asin(1.0)];
set nEigen 6
set lambdaN [eigen [expr $nEigen]];
set lambda1 [lindex $lambdaN 0];
set lambda2 [lindex $lambdaN 1];
set lambda3 [lindex $lambdaN 2];
set lambda4 [lindex $lambdaN 3];
set lambda5 [lindex $lambdaN 4];
set lambda6 [lindex $lambdaN 5];
set w1 [expr pow($lambda1, 0.5)];
set w2 [expr pow($lambda2, 0.5)];
set w3 [expr pow($lambda3, 0.5)];
set w4 [expr pow($lambda4, 0.5)];
set w5 [expr pow($lambda5, 0.5)];
set w6 [expr pow($lambda6, 0.5)];
set T1 [expr round(2.0*$pi/$w1 *1000.)/1000.];
set T2 [expr round(2.0*$pi/$w2 *1000.)/1000.];
set T3 [expr round(2.0*$pi/$w3 *1000.)/1000.];
set T4 [expr round(2.0*$pi/$w4 *1000.)/1000.];
set T5 [expr round(2.0*$pi/$w5 *1000.)/1000.];
set T6 [expr round(2.0*$pi/$w6 *1000.)/1000.];
puts "T1 = $T1 s";
puts "T2 = $T2 s";
puts "T3 = $T3 s";

set mode [list]
for {set i 1} {$i <= $NStory} {incr i} {
    lappend mode [expr [nodeEigenvector 17 $i 1]]
    lappend mode [expr [nodeEigenvector 10 $i 1]]
    lappend mode [expr [nodeEigenvector 5  $i 1]]
    lappend mode [expr [nodeEigenvector 12 $i 1]]
    lappend mode [expr [nodeEigenvector 14 $i 1]]
    lappend mode [expr [nodeEigenvector 8  $i 1]]
    set file_mode [open "$MainFolder/$SubFolder/mode$i.out" w]
    foreach val $mode {puts $file_mode $val}
    close $file_mode
    if {$i == 1} {set mode_list $mode}
    set mode [list]
};

set file_T [open "$MainFolder/$SubFolder/Period.out" w];
puts $file_T $T1;
puts $file_T $T2;
puts $file_T $T3;
close $file_T;


# --------------------------- Static gravity analysis ----------------------------

pattern Plain 100 Linear {

    # TODO Write gravity load from analysis_steps.tcl
	load 16 0.0 242400.0 0.0
	load 27 0.0 242400.0 0.0
	load 15 0.0 -273700.0 0.0
	load 17 0.0 -273700.0 0.0
	load 11 0.0 -231200.0 0.0
	load 26 0.0 -231200.0 0.0
	load 4 0.0 -257600.0 0.0
	load 10 0.0 -257600.0 0.0
	load 6 0.0 -243000.0 0.0
	load 22 0.0 -243000.0 0.0
	load 1 0.0 -274400.0 0.0
	load 5 0.0 -274400.0 0.0
	load 13 0.0 -233800.0 0.0
	load 23 0.0 -233800.0 0.0
	load 2 0.0 -263700.0 0.0
	load 12 0.0 -263700.0 0.0
	load 19 0.0 -240100.0 0.0
	load 20 0.0 -240100.0 0.0
	load 3 0.0 -272300.0 0.0
	load 14 0.0 -272300.0 0.0
	load 9 0.0 -197900.0 0.0
	load 24 0.0 -197900.0 0.0
	load 7 0.0 -267500.0 0.0
	load 8 0.0 -267500.0 0.0

}

wipeAnalysis
constraints Plain;
numberer RCM;
system BandGeneral;
test NormDispIncr 1.0e-5 60;
algorithm Newton;
integrator LoadControl 0.1;
analysis Static;
analyze 10;
loadConst -time 0.0;


# ---------------------------- Time history analysis -----------------------------

if {$ShowAnimation == 1} {DisplayModel3D DeformedShape 5.00 100 100 1000 1500};

if {$EQ == 1} {

    # Rayleigh damping
    set zeta 0.05;
    set a0 [expr $zeta*2.0*$w1*$w3/($w1 + $w3)];
    set a1 [expr $zeta*2.0/($w1 + $w3)];
    rayleigh $a0 0.0 $a1 0.0;

    # Ground motion acceleration file input
    set g 9810.0;
    set AccelSeries "Series -dt $GMdt -filePath $GMFile -factor [expr $EqSF * $g]";
    pattern UniformExcitation 200 1 -accel $AccelSeries;
    set totTime [expr $GMduration + $FVduration];
    set CollapseDrift 0.1;
    set MaxAnalysisDrift 0.5;
    set result [TimeHistorySolver $GMdt $GMduration $story_heights $MF_FloorNodes $CollapseDrift $MaxAnalysisDrift $GMname $maxRunTime $temp];
    set status [lindex $result 0];
    set controlled_time [lindex $result 1];
    puts "Running status: $status";
    puts "Controlled time: $controlled_time";

}


# ------------------------------ Pushover analysis -------------------------------

if {$PO == 1} {

    set m2 83.61;
    set m3 82.53;
    set m4 82.53;
    set m5 80.23;
    set m6 80.23;
    set m7 82.16;

    set F2 [expr $m2 * [lindex $mode_list 0]];
    set F3 [expr $m3 * [lindex $mode_list 1]];
    set F4 [expr $m4 * [lindex $mode_list 2]];
    set F5 [expr $m5 * [lindex $mode_list 3]];
    set F6 [expr $m6 * [lindex $mode_list 4]];
    set F7 [expr $m7 * [lindex $mode_list 5]];
    pattern Plain 222 Linear {
        load 17 $F2 0.0 0.0;
        load 10 $F3 0.0 0.0;
        load 5  $F4 0.0 0.0;
        load 12 $F5 0.0 0.0;
        load 14 $F6 0.0 0.0;
        load 8  $F7 0.0 0.0;
    };
    set CtrlNode 8;
    set maxRoofDrift 0.1;  # $$$
    set Dmax [expr $maxRoofDrift * $Floor7];
    set Dincr [expr 0.5];
    set result [PushoverAnalysis $CtrlNode $Dmax $Dincr $maxRunTime];
    set status [lindex $result 0];
    set roofDisp [lindex $result 1];
    puts "Running status: $status";
    puts "Roof displacement: $roofDisp";
    puts "Roof drift ratio: [expr $roofDisp / $HBuilding]";

}

wipe all;
